#! /bin/sh

bspc config border_width        2
bspc config window_gap          5

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

bspc monitor DVI-I-1 -d 6 7 8 9 0
bspc monitor DVI-I-0 -d 1 2 3 4 5

bspc rule -a mumble floating-true
