#! /bin/sh

xsetroot -cursor_name left_ptr &

bspc config border_width        1
bspc config window_gap          0

bspc config split_ratio         0.5
bspc config borderless_monocle true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

bspc monitor -d 1 2 3 4 5 6 7 8 9 0


#bspc rule -a mumble follow=off

